//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inventaire_APC
{
    using System;
    using System.Collections.Generic;
    
    public partial class bureauxSet
    {
        public bureauxSet()
        {
            this.inventaires_bureauSet = new HashSet<inventaires_bureauSet>();
        }
    
        public int id_bureau { get; set; }
        public string nom_bureau { get; set; }
        public int services_antennes_id_service { get; set; }
        public int etat_bureau { get; set; }
    
        public virtual ICollection<inventaires_bureauSet> inventaires_bureauSet { get; set; }
        public virtual services_antennesSet services_antennesSet { get; set; }
    }
}
