//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inventaire_APC
{
    using System;
    using System.Collections.Generic;
    
    public partial class inventaires_bureauSet
    {
        public int id_inventaire { get; set; }
        public int numero_inventaire { get; set; }
        public string nom_inventaire { get; set; }
        public int nombre_inventaire { get; set; }
        public string refrence_inventaire { get; set; }
        public string remarque_inventaire { get; set; }
        public int bureaux_id_bureau { get; set; }
        public Nullable<int> code_equippent_insert { get; set; }
    
        public virtual bureauxSet bureauxSet { get; set; }
    }
}
