//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inventaire_APC
{
    using System;
    using System.Collections.Generic;
    
    public partial class liste_equipementSet
    {
        public int id_equipement { get; set; }
        public string nom_equipement { get; set; }
        public Nullable<int> quantite { get; set; }
    }
}
