//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inventaire_APC
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class inventaire_apcEntities : DbContext
    {
        public inventaire_apcEntities()
            : base("name=inventaire_apcEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<bureauxSet> bureauxSet { get; set; }
        public virtual DbSet<inventaires_bureauSet> inventaires_bureauSet { get; set; }
        public virtual DbSet<liste_equipementSet> liste_equipementSet { get; set; }
        public virtual DbSet<services_antennesSet> services_antennesSet { get; set; }
        public virtual DbSet<login_tab> login_tabSet { get; set; }
    }
}
