//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inventaire_APC
{
    using System;
    using System.Collections.Generic;
    
    public partial class services_antennesSet
    {
        public services_antennesSet()
        {
            this.bureauxSet = new HashSet<bureauxSet>();
        }
    
        public int id_service { get; set; }
        public string nom_service { get; set; }
    
        public virtual ICollection<bureauxSet> bureauxSet { get; set; }
    }
}
